version: "3.8"

services:
  dst:
    build: .
    image: dst-dedicated:latest

    env_file:
      - ./env/.env

    ports:
      - "10999:10999/udp" # Master game
      - "27016:27016/udp"
      - "8766:8766/udp"

      - "10998:10998/udp" # Caves game
      - "27017:27017/udp"
      - "8767:8767/udp"

    volumes:
      - ./data:/home/dst/.klei/DoNotStarveTogether
      - ./data/mods:/home/dst/dst_server/mods

      # 🔥 QUAN TRỌNG: persist Steam Workshop
      - ./steam:/home/dst/.steam

    restart: unless-stopped

    # vẫn dùng root nhưng sẽ drop về dst trong entrypoint
    user: "0:0"

  mod-updater:
    image: dst-dedicated:latest
    env_file:
      - ./env/.env
    command: ["/workspace/scripts/reset_and_install_mods_docker.sh"]
    volumes:
      - ./:/workspace
      - ./data:/home/dst/.klei/DoNotStarveTogether
      - ./data/mods:/home/dst/dst_server/mods
      - ./steam:/home/dst/.steam
    profiles:
      - tools
    user: "0:0"

  access-manager:
    image: dst-dedicated:latest
    env_file:
      - ./env/.env
    command: ["/workspace/scripts/set_access_lists.sh"]
    volumes:
      - ./:/workspace
      - ./data:/home/dst/.klei/DoNotStarveTogether
    profiles:
      - tools
    user: "0:0"