#!/bin/bash
# scripts/_lib.sh — Shared functions for DST server management

set -euo pipefail

# ═══════════════════════════════════════════════════════════
#  COLOR DEFINITIONS
# ═══════════════════════════════════════════════════════════
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'  # No Color

# ═══════════════════════════════════════════════════════════
#  LOGGING FUNCTIONS
# ═══════════════════════════════════════════════════════════

log() {
    echo -e "${GREEN}[DST-SERVER]${NC} $*"
}

warn() {
    echo -e "${YELLOW}[WARNING]${NC} $*" >&2
}

err() {
    echo -e "${RED}[ERROR]${NC} $*" >&2
    exit 1
}

info() {
    echo -e "${BLUE}[INFO]${NC} $*"
}

success() {
    echo -e "${GREEN}✅ $*${NC}"
}

debug() {
    if [[ "${DEBUG:-0}" == "1" ]]; then
        echo -e "${CYAN}[DEBUG]${NC} $*" >&2
    fi
}

# ═══════════════════════════════════════════════════════════
#  ENVIRONMENT & PATHS
# ═══════════════════════════════════════════════════════════

# Get script directory (handles both direct execution and sourcing)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROJECT_ROOT="${SCRIPT_DIR}"
DATA_DIR="${PROJECT_ROOT}/data"
CLUSTER_DIR="${DATA_DIR}/cluster"
MASTER_DIR="${DATA_DIR}/master"
CAVES_DIR="${DATA_DIR}/caves"
MODS_DIR="${DATA_DIR}/mods"
BACKUPS_DIR="${DATA_DIR}/backups"
DST_SERVER="${PROJECT_ROOT}/dst_server/bin64/dontstarve_dedicated_server_nullrenderer_x64"
DST_SERVER_APP="${PROJECT_ROOT}/dst_server/dontstarve_dedicated_server_nullrenderer.app/Contents/MacOS/dontstarve_dedicated_server_nullrenderer"
DST_SERVER_STEAM_BIN64="${PROJECT_ROOT}/dst_server/bin64/dontstarve_dedicated_server_nullrenderer"

# ═══════════════════════════════════════════════════════════
#  ENV LOADING
# ═══════════════════════════════════════════════════════════

source_env() {
    local env_file="${PROJECT_ROOT}/env/.env"
    if [[ ! -f "$env_file" ]]; then
        err "env/.env not found. Copy env/.env.template to env/.env first."
    fi
    # Safely source env file
    set -a
    source "$env_file"
    set +a
}

# Find steamclient.dylib used by libsteam_api during server registration.
resolve_steamclient_dylib() {
    local candidates=(
        "${PROJECT_ROOT}/dst_server/Library/steamclient.dylib"
        "${DST_SERVER%/*}/../Library/steamclient.dylib"
        "${HOME}/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/steamclient.dylib"
    )
    local path
    for path in "${candidates[@]}"; do
        if [[ -f "$path" ]]; then
            echo "$path"
            return 0
        fi
    done
    return 1
}

sync_mod_configs() {
    local mods_file="${PROJECT_ROOT}/env/mods.txt"
    local runtime_cluster_dir="${HOME}/Documents/Klei/DoNotStarveTogether/${DST_CLUSTER_NAME}"
    local runtime_master_dir="${runtime_cluster_dir}/Master"
    local runtime_caves_dir="${runtime_cluster_dir}/Caves"
    local runtime_mods_dir="${runtime_cluster_dir}/mods"
    local -a mod_ids=()
    local line

    if [[ -f "$mods_file" ]]; then
        while IFS= read -r line; do
            line="${line%%#*}"
            line="$(echo "$line" | xargs)"
            [[ -n "$line" ]] || continue
            mod_ids+=("$line")
        done < "$mods_file"
    else
        warn "env/mods.txt not found; writing empty mod configuration"
    fi

    local -a mods_setup_targets=(
        "${MODS_DIR}/dedicated_server_mods_setup.lua"
        "${PROJECT_ROOT}/dst_server/mods/dedicated_server_mods_setup.lua"
        "${runtime_mods_dir}/dedicated_server_mods_setup.lua"
    )
    local target
    local mod_id

    for target in "${mods_setup_targets[@]}"; do
        mkdir -p "$(dirname "$target")"
        {
            echo "-- Auto-generated by scripts/_lib.sh:sync_mod_configs"
            echo "-- Source: env/mods.txt"
            for mod_id in "${mod_ids[@]}"; do
                echo "ServerModSetup(\"${mod_id}\")"
            done
        } > "$target"
    done

    local -a modoverrides_targets=(
        "${MASTER_DIR}/modoverrides.lua"
        "${CAVES_DIR}/modoverrides.lua"
        "${runtime_master_dir}/modoverrides.lua"
        "${runtime_caves_dir}/modoverrides.lua"
    )

    for target in "${modoverrides_targets[@]}"; do
        mkdir -p "$(dirname "$target")"
        {
            echo "return {"
            for mod_id in "${mod_ids[@]}"; do
                echo "    [\"workshop-${mod_id}\"] = { enabled = true, configuration_options = {} },"
            done
            echo "}"
        } > "$target"
    done

    log "Synced ${#mod_ids[@]} mod(s) into DST runtime config"
}

# ═══════════════════════════════════════════════════════════
#  UTILITY FUNCTIONS
# ═══════════════════════════════════════════════════════════

# Check if screen session exists
session_exists() {
    local session_name="$1"
    screen -list 2>/dev/null | grep -q "\.${session_name}\s" && return 0 || return 1
}

# Get PID of screen session
get_session_pid() {
    local session_name="$1"
    local pid=$(screen -list 2>/dev/null | grep "\.${session_name}\s" | grep -o '[0-9]\+' | head -1)
    [[ -n "$pid" ]] && echo "$pid" || echo ""
}

# Check if port is listening
port_listening() {
    local port="$1"
    local protocol="${2:-udp}"
    lsof -i "${protocol}:${port}" >/dev/null 2>&1 && return 0 || return 1
}

# Format timestamp for backups
timestamp() {
    date +%Y%m%d-%H%M%S
}

# Get human-readable file size
human_size() {
    local bytes="$1"
    if [[ $bytes -ge 1073741824 ]]; then
        echo "$((bytes / 1073741824))GB"
    elif [[ $bytes -ge 1048576 ]]; then
        echo "$((bytes / 1048576))MB"
    elif [[ $bytes -ge 1024 ]]; then
        echo "$((bytes / 1024))KB"
    else
        echo "${bytes}B"
    fi
}

# Check if DST binary exists
dst_binary_exists() {
    [[ -x "$DST_SERVER" ]]
}

dst_runtime_binary() {
    if [[ -x "$DST_SERVER_STEAM_BIN64" ]]; then
        echo "$DST_SERVER_STEAM_BIN64"
    elif [[ -x "$DST_SERVER_APP" ]]; then
        echo "$DST_SERVER_APP"
    else
        echo "$DST_SERVER"
    fi
}

# Check if config files exist
config_exists() {
    [[ -f "${CLUSTER_DIR}/cluster.ini" && -f "${CLUSTER_DIR}/cluster_token.txt" ]]
}

export -f log warn err info success debug
export -f session_exists get_session_pid port_listening timestamp human_size
export -f dst_binary_exists config_exists dst_runtime_binary
export -f source_env resolve_steamclient_dylib sync_mod_configs
export PROJECT_ROOT DATA_DIR CLUSTER_DIR MASTER_DIR CAVES_DIR MODS_DIR BACKUPS_DIR DST_SERVER DST_SERVER_APP DST_SERVER_STEAM_BIN64
export RED GREEN YELLOW BLUE CYAN NC
