#!/usr/bin/env bash
# Reset and reinstall DST workshop mods inside Docker environment.
set -euo pipefail

DST_CLUSTER_NAME="${DST_CLUSTER_NAME:-MyDediServer}"
DST_INSTALL_DIR="${DST_INSTALL_DIR:-/home/dst/dst_server}"
DST_CLUSTER_ROOT="${DST_CLUSTER_ROOT:-/home/dst/.klei/DoNotStarveTogether}"
DST_CLUSTER_DIR="${DST_CLUSTER_DIR:-${DST_CLUSTER_ROOT}/${DST_CLUSTER_NAME}}"
MODS_DEST="${MODS_DEST:-${DST_INSTALL_DIR}/mods}"
MODS_FILE="${MODS_FILE:-/workspace/env/mods.txt}"
DST_APP_ID="${DST_APP_ID:-322330}"
STEAMCMD_BIN="${STEAMCMD_BIN:-${HOME}/steamcmd/steamcmd.sh}"

MASTER_DIR="${DST_CLUSTER_DIR}/Master"
CAVES_DIR="${DST_CLUSTER_DIR}/Caves"

if [[ ! -f "${MODS_FILE}" ]]; then
  echo "ERROR: MODS_FILE not found: ${MODS_FILE}" >&2
  exit 1
fi

mkdir -p "${MODS_DEST}" "${MASTER_DIR}" "${CAVES_DIR}"

MOD_IDS=()
while IFS= read -r line; do
  line="$(echo "${line}" | sed 's/[[:space:]]//g')"
  if [[ -n "${line}" && "${line}" != \#* ]]; then
    MOD_IDS+=("${line}")
  fi
done < "${MODS_FILE}"
if [[ ${#MOD_IDS[@]} -eq 0 ]]; then
  echo "ERROR: no mod IDs found in ${MODS_FILE}" >&2
  exit 1
fi

echo "== Step 1: Reset old mod cache =="
rm -rf "${MODS_DEST}"/workshop-* 2>/dev/null || true
rm -rf "${HOME}/Steam/steamapps/workshop/content/${DST_APP_ID}"/* 2>/dev/null || true
rm -rf "${HOME}/steamcmd/steamapps/workshop/content/${DST_APP_ID}"/* 2>/dev/null || true

if [[ "${DST_TEST_MODE:-0}" != "1" ]]; then
  if [[ ! -x "${STEAMCMD_BIN}" ]]; then
    echo "ERROR: steamcmd not found at ${STEAMCMD_BIN}" >&2
    exit 1
  fi

  echo "== Step 2: Download latest workshop mods =="
  STEAMCMD_ARGS=(+login anonymous)
  for id in "${MOD_IDS[@]}"; do
    STEAMCMD_ARGS+=(+workshop_download_item "${DST_APP_ID}" "${id}" validate)
  done
  STEAMCMD_ARGS+=(+quit)
  "${STEAMCMD_BIN}" "${STEAMCMD_ARGS[@]}" || true
fi

WORKSHOP_DIR=""
if [[ -d "${HOME}/Steam/steamapps/workshop/content/${DST_APP_ID}" ]]; then
  WORKSHOP_DIR="${HOME}/Steam/steamapps/workshop/content/${DST_APP_ID}"
elif [[ -d "${HOME}/steamcmd/steamapps/workshop/content/${DST_APP_ID}" ]]; then
  WORKSHOP_DIR="${HOME}/steamcmd/steamapps/workshop/content/${DST_APP_ID}"
fi

declare -a SUCCESS_IDS=()
declare -a FAILED_IDS=()

if [[ "${DST_TEST_MODE:-0}" == "1" ]]; then
  SUCCESS_IDS=("${MOD_IDS[@]}")
else
  if [[ -z "${WORKSHOP_DIR}" ]]; then
    echo "ERROR: workshop directory not found after download" >&2
    exit 1
  fi

  echo "== Step 3: Copy workshop mods to server mods directory =="
  for id in "${MOD_IDS[@]}"; do
    src="${WORKSHOP_DIR}/${id}"
    dest="${MODS_DEST}/workshop-${id}"
    if [[ -d "${src}" ]]; then
      rm -rf "${dest}"
      cp -R "${src}" "${dest}"
      if [[ -f "${dest}/modinfo.lua" ]]; then
        SUCCESS_IDS+=("${id}")
      else
        FAILED_IDS+=("${id}:missing modinfo.lua")
      fi
    else
      FAILED_IDS+=("${id}:not downloaded")
    fi
  done
fi

if [[ ${#SUCCESS_IDS[@]} -eq 0 ]]; then
  echo "ERROR: 0/${#MOD_IDS[@]} mods installed successfully" >&2
  if [[ ${#FAILED_IDS[@]} -gt 0 ]]; then
    printf '%s\n' "${FAILED_IDS[@]}" >&2
  fi
  exit 1
fi

{
  echo "-- Auto-generated by reset_and_install_mods_docker.sh"
  for id in "${SUCCESS_IDS[@]}"; do
    echo "ServerModSetup(\"${id}\")"
  done
} > "${MODS_DEST}/dedicated_server_mods_setup.lua"

{
  echo "return {"
  for id in "${SUCCESS_IDS[@]}"; do
    echo "  [\"workshop-${id}\"] = { enabled = true, configuration_options = {} },"
  done
  echo "}"
} > "${MASTER_DIR}/modoverrides.lua"

cp "${MASTER_DIR}/modoverrides.lua" "${CAVES_DIR}/modoverrides.lua"

echo "== Result =="
echo "Success: ${#SUCCESS_IDS[@]}/${#MOD_IDS[@]}"
if [[ ${#FAILED_IDS[@]} -gt 0 ]]; then
  echo "Failed:"
  printf '  %s\n' "${FAILED_IDS[@]}"
fi
